# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agendamento_pb2 as agendamento__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in agendamento_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgendamentoMedicoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AgendarConsulta = channel.unary_unary(
                '/agendamento.AgendamentoMedico/AgendarConsulta',
                request_serializer=agendamento__pb2.AgendarConsultaRequest.SerializeToString,
                response_deserializer=agendamento__pb2.AgendarConsultaResponse.FromString,
                _registered_method=True)
        self.BuscarConsulta = channel.unary_unary(
                '/agendamento.AgendamentoMedico/BuscarConsulta',
                request_serializer=agendamento__pb2.GerenciarConsultaRequest.SerializeToString,
                response_deserializer=agendamento__pb2.GerenciarConsultaResponse.FromString,
                _registered_method=True)
        self.CancelarConsulta = channel.unary_unary(
                '/agendamento.AgendamentoMedico/CancelarConsulta',
                request_serializer=agendamento__pb2.GerenciarConsultaRequest.SerializeToString,
                response_deserializer=agendamento__pb2.GerenciarConsultaResponse.FromString,
                _registered_method=True)


class AgendamentoMedicoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AgendarConsulta(self, request, context):
        """Cadastra uma nova consulta e retorna um código único
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarConsulta(self, request, context):
        """Busca os detalhes de uma consulta usando seu código
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelarConsulta(self, request, context):
        """Cancela uma consulta usando seu código
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgendamentoMedicoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AgendarConsulta': grpc.unary_unary_rpc_method_handler(
                    servicer.AgendarConsulta,
                    request_deserializer=agendamento__pb2.AgendarConsultaRequest.FromString,
                    response_serializer=agendamento__pb2.AgendarConsultaResponse.SerializeToString,
            ),
            'BuscarConsulta': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarConsulta,
                    request_deserializer=agendamento__pb2.GerenciarConsultaRequest.FromString,
                    response_serializer=agendamento__pb2.GerenciarConsultaResponse.SerializeToString,
            ),
            'CancelarConsulta': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelarConsulta,
                    request_deserializer=agendamento__pb2.GerenciarConsultaRequest.FromString,
                    response_serializer=agendamento__pb2.GerenciarConsultaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agendamento.AgendamentoMedico', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agendamento.AgendamentoMedico', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgendamentoMedico(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AgendarConsulta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agendamento.AgendamentoMedico/AgendarConsulta',
            agendamento__pb2.AgendarConsultaRequest.SerializeToString,
            agendamento__pb2.AgendarConsultaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuscarConsulta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agendamento.AgendamentoMedico/BuscarConsulta',
            agendamento__pb2.GerenciarConsultaRequest.SerializeToString,
            agendamento__pb2.GerenciarConsultaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelarConsulta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agendamento.AgendamentoMedico/CancelarConsulta',
            agendamento__pb2.GerenciarConsultaRequest.SerializeToString,
            agendamento__pb2.GerenciarConsultaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
