# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agendamento.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'agendamento.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61gendamento.proto\x12\x0b\x61gendamento\"`\n\x08\x43onsulta\x12\x13\n\x0bid_consulta\x18\x01 \x01(\t\x12\x10\n\x08paciente\x18\x02 \x01(\t\x12\x0e\n\x06medico\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t\x12\x0f\n\x07horario\x18\x05 \x01(\t\"Y\n\x16\x41gendarConsultaRequest\x12\x10\n\x08paciente\x18\x01 \x01(\t\x12\x0e\n\x06medico\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x12\x0f\n\x07horario\x18\x04 \x01(\t\"X\n\x17\x41gendarConsultaResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\x12\x1a\n\x12id_consulta_gerado\x18\x03 \x01(\t\"/\n\x18GerenciarConsultaRequest\x12\x13\n\x0bid_consulta\x18\x01 \x01(\t\"g\n\x19GerenciarConsultaResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\x12\'\n\x08\x63onsulta\x18\x03 \x01(\x0b\x32\x15.agendamento.Consulta2\xb5\x02\n\x11\x41gendamentoMedico\x12\\\n\x0f\x41gendarConsulta\x12#.agendamento.AgendarConsultaRequest\x1a$.agendamento.AgendarConsultaResponse\x12_\n\x0e\x42uscarConsulta\x12%.agendamento.GerenciarConsultaRequest\x1a&.agendamento.GerenciarConsultaResponse\x12\x61\n\x10\x43\x61ncelarConsulta\x12%.agendamento.GerenciarConsultaRequest\x1a&.agendamento.GerenciarConsultaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agendamento_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONSULTA']._serialized_start=34
  _globals['_CONSULTA']._serialized_end=130
  _globals['_AGENDARCONSULTAREQUEST']._serialized_start=132
  _globals['_AGENDARCONSULTAREQUEST']._serialized_end=221
  _globals['_AGENDARCONSULTARESPONSE']._serialized_start=223
  _globals['_AGENDARCONSULTARESPONSE']._serialized_end=311
  _globals['_GERENCIARCONSULTAREQUEST']._serialized_start=313
  _globals['_GERENCIARCONSULTAREQUEST']._serialized_end=360
  _globals['_GERENCIARCONSULTARESPONSE']._serialized_start=362
  _globals['_GERENCIARCONSULTARESPONSE']._serialized_end=465
  _globals['_AGENDAMENTOMEDICO']._serialized_start=468
  _globals['_AGENDAMENTOMEDICO']._serialized_end=777
# @@protoc_insertion_point(module_scope)
